// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryManagementSystem.Models
{
    public partial class BookLimits
    {
        public int BookLimit { get; set; }
    }
}