// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryManagementSystem.Models
{
    public partial class Books
    {
        public Books()
        {
            Records = new HashSet<Records>();
            Returns = new HashSet<Returns>();
        }

        public int BookId { get; set; }
        public string BookName { get; set; }
        public int? NumberOfPage { get; set; }
        public int? StockAmount { get; set; }
        public int? AuthorId { get; set; }
        public int? CategoryId { get; set; }
        public DateTime? ProductionYear { get; set; }

        public virtual Authors Author { get; set; }
        public virtual Categories Category { get; set; }
        public virtual ICollection<Records> Records { get; set; }
        public virtual ICollection<Returns> Returns { get; set; }
    }
}