// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryManagementSystem.Models
{
    public partial class Ranks
    {
        public Ranks()
        {
            Users = new HashSet<Users>();
        }

        public int RankId { get; set; }
        public string RankName { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}