// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryManagementSystem.Models
{
    public partial class Returns
    {
        public int ReturnId { get; set; }
        public int BookId { get; set; }
        public int? UserId { get; set; }
        public DateTime? AcquisitionDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        public DateTime? Deadline { get; set; }

        public virtual Books Book { get; set; }
        public virtual Users User { get; set; }
    }
}