// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryManagementSystem.Models
{
    public partial class Users
    {
        public Users()
        {
            Records = new HashSet<Records>();
            Returns = new HashSet<Returns>();
        }

        public int UserId { get; set; }
        public int? UserTypeId { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RegisterIp { get; set; }
        public DateTime? RegisterDate { get; set; }
        public string SaltOfPw { get; set; }
        public int? RankId { get; set; }

        public virtual Ranks Rank { get; set; }
        public virtual UserTypes UserType { get; set; }
        public virtual ICollection<Records> Records { get; set; }
        public virtual ICollection<Returns> Returns { get; set; }
    }
}